### ISSUE TITLE
[Bug]: Addon summary automatically adds link html markup to text

### ISSUE THREAD

**Issue by axlwaii** [mozilla/addons#15369]
### What happened?

Addon Pages automatically adds link markup for text that matches link patterns. The links go to `prod.outgoing.prod.webservices.mozgcp.net', but they are not clickable or functional.

e.g.
- [Ecosia — The search engine that plants trees](https://addons.mozilla.org/en-US/firefox/addon/ecosia-the-green-search/)
- [Org Capture](https://addons.mozilla.org/en-US/firefox/addon/org-capture/)

### What did you expect to happen?

Links are either ...
- clickable and no HTML markup is visible
- or markup is removed if not intentionally added

### Is there an existing issue for this?

- [x] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1446)

**Comment by diox** [comment]
We started preventing links in summaries and eventually decided to be more aggressive against them, to avoid spam/malicious links (https://github.com/mozilla/addons/issues/15254)

Those add-ons already had links in summaries and should be cleaned up. We need to run some numbers to see if it makes sense to automate that or simply ask developers to fix the text themselves.

**Comment by Rob--W** [comment]
Anecdotally of course, but two of my add-ons are affected by this. These are auto-generated, which makes it feasible to parse/replace automatically.

https://addons.mozilla.org/en-US/firefox/addon/crxviewer/

> `View source code of Firefox add-ons and Chrome extensions (crx/nex/xpi) from <a href="http://addons.mozilla.org" rel="nofollow">addons.mozilla.org</a>, the Chrome Webstore and elsewhere, with CRX Viewer (crxviewer).`

https://addons.mozilla.org/en-US/firefox/addon/dont-slack-redir/

> `An efficient way to prevent Slack from replacing links with <a href="https://prod.outgoing.prod.webservices.mozgcp.net/v1/b722ca95d5c185ef754582cdedd5c7e09925155cee456b493441c6b5592ad915/http%3A//slack-redir.net" rel="nofollow">slack-redir.net</a>, while still protecting privacy (against referrer leakage).`

**Comment by diox** [comment]
There is a significant number of add-ons impacted: 4.3k publicly listed extensions.

**Comment by diox** [comment]
I think we should copy `localized_string` to `localized_string_clean` for affected summaries. This would leave the link if it was added before we started preventing their addition, but without the HTMLification, so it would simply render as plain text.

**Comment by diox** [comment]
We're going to fix this by running a command. 

On dev:
It should fix this add-on (which has HTML generated before the change, that we should clean up):
https://addons-dev.allizom.org/en-US/firefox/addon/dmitlichess_176mb/

But leave this one (which has HTML entered after the change, already escaped):
https://addons-dev.allizom.org/en-US/firefox/addon/would-escape-html/

**Comment by diox** [comment]
The task to clean up the summaries containing HTML generated because of URLs that had previously been added ran in production.

**Comment by Rob--W** [comment]
I just came across an add-on that has `&lt;` and `&gt;` in its description: https://addons.mozilla.org/en-US/firefox/addon/open-new-tab-in-container/

> `Open a newtab in a specified container (with the command line or address bar) via a url in the form ext+newtabcontainer://&lt;container_name&gt;`

Published on 2024-04-29, which predates the AMO changes. Was it possibly affected by the same issue, yet not fixed by the migration above?
